### PR TITLE
Update additionalExtensionDependencies to accept a list of dependency

### PR DESCRIPTION
**Pull request by zhfeng**

### CODE REVIEW

**Comment by ppalaga** [comment]
@zhfeng the current syntax allow multiple additional deps in a single string, one just has to separate them by comma or whitespace. Is that not sufficient for some reason?

**Comment by ppalaga** [comment]
`GavSet.builder().includes(String)` does the splitting around here: https://github.com/l2x6/pom-tuner/blob/main/src/main/java/org/l2x6/pom/tuner/model/GavSet.java#L362

**Comment by ppalaga** [comment]
Hm... I see that `additionalExtensionDependencies` is not documented in https://github.com/jboss-fuse/camel-quarkus/blob/3.8.0-product/product/README.adoc - would you mind adding a line there?

**Comment by zhfeng** [comment]
OK, I get and thanks for explaination!

**Comment by zhfeng** [comment]
It works to add in a single line. Great!

**Pull request closed without merging**
