### PR TITLE
Override unlisted property by quarkus.metadata.unlisted in runtime pom

### PR DESCRIPTION
**Pull request by zhfeng**

### CODE REVIEW

**Comment by ppalaga** [comment]
Thanks @zhfeng, the new logic is useful, even for the community code.quarkus.io, where -- I assume -- the JVM only support status will perhaps be available one day.

For the product (i.e. the problem we are currently solving), I think `org.l2x6.cq.maven.prod.PlatformOverridesMojo.execute()` would be a better place to solve it. In that mojo we produce a single big json file that overrides some parts of the individual quarkus-extension.yaml files. That single big overrides file is then referenced in the prod platform to produce the effective config my combining the quarkus-extension.yaml files from the jars with the big overrides file.
I think we should add a piece of logic to `org.l2x6.cq.maven.prod.PlatformOverridesMojo.execute()` to override the `unlisted` attribute based on the info available in product.json, such as `org.l2x6.cq.maven.prod.Product.Extension.redhatSupportLevel()`. WDYT?

**Comment by zhfeng** [comment]
Good point - I will take a look and when do we run `PlatformOverridesMojo`?

**Comment by zhfeng** [comment]
Just adding the following code in the Mojo is OK?
```java
extModel.put("unlisted", "false");
```

**Comment by zhfeng** [comment]
@ppalaga I open https://github.com/l2x6/cq-maven-plugin/pull/367 to fix it in `PlatformOverridesMojo`

**Pull request merged**
