### PR TITLE
Camel 4 camel-package-manager moved to plexus-utils 4 - API changes

### PR DESCRIPTION
**Pull request by cunningt**
Changes to enable Camel 4 camel-package-maven-plugin (plexus-util upgrade occurred on Camel 4, requires API changes)

### CODE REVIEW

**Comment by cunningt** [comment]
Failing JDK11 tests because camel version is set to 4.0.0-RC2.

**Comment by ppalaga** [comment]
I tried to address some issues related to Camel 4 in https://github.com/l2x6/cq-maven-plugin/pull/257 . It is probably not all you had in mind in this PR. I must say I do not understand your commit message "camel-package-manager moved to plexus-utils 4" What is camel-package-manager? I never heart of it and I found no trace of it in Camel source tree.

**Comment by cunningt** [comment]
Sorry - camel-package-maven-plugin uses plexus-utils 4.     The direct use of ComponentDslMojo I think requires that we make changes to support this.

**Comment by ppalaga** [comment]
> camel-package-maven-plugin uses plexus-utils 4. 

Thanks for explaining!

> The direct use of ComponentDslMojo I think requires that we make changes to support this.

Hm... I wonder why they upgraded. Maven 3 is still at plexus-utils 3.5.1
image

But you mean it would work if we upgrade and add those few artifacts... Let's do it then. Would you please rebase this PR, possibly removing what addressed in https://github.com/l2x6/cq-maven-plugin/pull/257 ?

**Review by ppalaga — APPROVED** [review]

**Pull request merged**
