### PR TITLE
Initial commit of camel-spring-boot-prod-maven-plugin, documentation additions.

### PR DESCRIPTION
**Pull request by cunningt**
Initial commit of camel-spring-boot-prod-maven-plugin, documentation additions.

### CODE REVIEW

**Comment by cunningt** [comment]
@ppalaga Could you please hold off on merging?   I asked Freeman to take a look at the results on Monday.

**Comment by ppalaga** [comment]
Could you please check the CI failures, @cunningt ?

**Review by ppalaga — APPROVED** [review]

**Comment by ppalaga** [comment]
Should I release like this, @cunningt ? Or is there anything else coming?

**Comment by ppalaga** [comment]
I am releasing 2.21.0

**Comment by cunningt** [comment]
Sounds good to me!    I don't have anything to add at the moment.

**Comment by ppalaga** [comment]
2.21.0 artifacts are now available in Central

**Pull request merged**
